---
- hosts: all
  become: yes
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present

  - name: start web Servers
    service:
      name: apache2
      state: start    